version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Порт AMQP
      - "15672:15672" # Веб-интерфейс
    environment:
      RABBITMQ_DEFAULT_USER: admin  # Установите пользователя
      RABBITMQ_DEFAULT_PASS: admin  # Установите пароль

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NotificationQueue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

  # apigateway:
  #   build:
  #     context: ./ApiGateway
  #     dockerfile: Dockerfile
  #   ports:
  #     - "7000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   depends_on:
  #     - notificationqueue
  # notificationqueue:
  #   build:
  #     context: ./NotificationQueue
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
